# Generated by Django 4.2.16 on 2024-11-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_schedule_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
