# Generated by Django 4.2.16 on 2024-11-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_budget_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_income',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
