# Generated by Django 4.2.16 on 2024-11-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_schedule_is_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_book_data',
            name='memo',
            field=models.CharField(default=1, max_length=75),
            preserve_default=False,
        ),
    ]
