# Generated by Django 4.2.16 on 2024-11-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_alter_account_book_data_memo"),
    ]

    operations = [
        migrations.AddField(
            model_name="account_book_data",
            name="is_schedule",
            field=models.BooleanField(default=False),
        ),
    ]
