# Generated by Django 4.2.16 on 2024-11-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_account_book_data_is_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account_book_data",
            name="memo",
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
